---
- name: Configure Primary DNS Server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    # Pulling out DCs private IPs and setting them as dns servers
    - "{{ hostvars['carapice-dc-1']['xs_vm_def']['networks'][1]['ip'] | ipaddr('address') }}"
    - "{{ hostvars['carapice-dc-2']['xs_vm_def']['networks'][1]['ip'] | ipaddr('address') }}"

- name: Join Member server to Domain
  win_domain_membership:
    dns_domain_name: "{{domain_name}}"
    domain_admin_user: "{{domain_admin_username}}"
    domain_admin_password: "{{domain_admin_password}}"
    #domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
    state: domain
  register: domain_state

- name: Reboot
  win_reboot:
  when: domain_state.reboot_required
- name: wait for Server to come back online
  wait_for_connection:
      delay: 0 # not required. Number of seconds to wait before starting to poll.
      sleep: 5 # not required. Number of seconds to sleep between checks.
      connect_timeout: 500 # not required. Maximum number of seconds to wait for a connection to happen before closing and retrying.
      timeout: 600 # not required. Maximum number of seconds to wait for.